/**
 * pf-hello-world plugin handlers — generated from cookbook/pocketflow-hello-world.
 *
 * Idempotent FLOW_DEFINE on each run keeps the plugin file as the
 * source of truth. Form values flow into the Python flow via shared state.
 *
 * Generated by scripts/cookbook-to-plugin.mjs. Hand-edit as needed.
 */

const FLOW_SOURCE = "\"\"\"\npf-hello-world — generated from cookbook/pocketflow-hello-world\n\nGenerated by scripts/cookbook-to-plugin.mjs. Edit the plugin's handlers.js\n(FLOW_SOURCE constant) to customize. Each click on the plugin re-saves\nthe flow to ~/.agentidev/flows/pf-hello-world.py.\n\"\"\"\n# === flow.py ===\nfrom pocketflow import Node, Flow\nfrom agentidev_llm import call_llm\n\n# An example node and flow\n# Please replace this with your own node and flow\nclass AnswerNode(Node):\n    def prep(self, shared):\n        # Read question from shared\n        return shared[\"question\"]\n    \n    def exec(self, question):\n        return call_llm(question)\n    \n    def post(self, shared, prep_res, exec_res):\n        # Store the answer in shared\n        shared[\"answer\"] = exec_res\n\nanswer_node = AnswerNode()\nqa_flow = Flow(start=answer_node)\n\n\n# === main.py ===\n# (cross-file import elided — single concatenated source)\n\n# Example main function\n# Please replace this with your own main function\ndef main():\n    shared = {\n        \"question\": \"In one sentence, what's the end of universe?\",\n        \"answer\": None\n    }\n\n    qa_flow.run(shared)\n    print(\"Question:\", shared[\"question\"])\n    print(\"Answer:\", shared[\"answer\"])\n\n\nif __name__ == \"__main__\":\n    import json, sys\n    shared = {}\n    if not sys.stdin.isatty():\n        raw = sys.stdin.read()\n        if raw.strip():\n            try: shared = json.loads(raw)\n            except json.JSONDecodeError: shared = {}\n    try:\n        qa_flow.run(shared)\n    except Exception as e:\n        shared[\"error\"] = str(e)\n    json.dump(shared, sys.stdout, indent=2, default=str)\n    sys.stdout.write(\"\\n\")\n";

const FLOW_NAME = "pf-hello-world";
const PLUGIN_ID = "pf-hello-world";

export function register(handlers) {
  handlers["PF_HELLO_WORLD"] = async (msg) => {
    const defineRes = await handlers['FLOW_DEFINE']({ name: FLOW_NAME, source: FLOW_SOURCE });
    if (!defineRes.success) {
      return { success: false, error: 'flow define failed: ' + (defineRes.error || 'unknown') };
    }
    // Pass the form values as the initial shared state. Field names should
    // match the keys the flow's prep() reads from shared.
    const shared = Object.assign({}, msg || {});
    delete shared.type; // dispatch metadata, not for the flow
    const runRes = await handlers['FLOW_RUN']({
      name: FLOW_NAME,
      pluginId: PLUGIN_ID,
      shared,
      timeout: 90000,
    });
    if (!runRes.success) {
      return { success: false, error: 'flow run failed: ' + (runRes.error || 'unknown'), stderr: runRes.stderr };
    }
    const final = runRes.shared || {};
    return { success: !final.error, shared: final, error: final.error || null };
  };
}
