/**
 * SmartClient AI Renderer — walks LLM-generated JSON config trees
 * and creates SmartClient components. No eval of LLM output.
 *
 * LLM generates action descriptors (_action), renderer maps them
 * to real SmartClient function calls via ACTION_MAP.
 */

// Only these SmartClient types can be instantiated
const ALLOWED_TYPES = new Set([
  'VLayout', 'HLayout', 'ListGrid', 'DynamicForm', 'Button', 'Label',
  'TabSet', 'Tab', 'DetailViewer', 'SectionStack', 'HTMLFlow',
  'Window', 'ToolStrip', 'ToolStripButton',
  'PortalLayout', 'Portlet', 'Canvas', 'Progressbar', 'ImgButton',
  'ToolStripSeparator', 'ToolStripMenuButton', 'Menu',
  'ForgeListGrid', 'ForgeWizard', 'ForgeFilterBar',
]);

// Track created components for cleanup
let generatedComponents = [];
let generatedDataSources = [];

// Resolve a component ID from the current render batch
const componentRegistry = {};

function resolveRef(id) {
  return componentRegistry[id] || (typeof window[id] !== 'undefined' ? window[id] : null);
}

// ---- Dispatch bridge action via postMessage ----
//
// Two flavors:
//   dispatchAction(type, payload)            — fire-and-forget; numeric id.
//   _rendererDispatchAsync(type, payload)    — Promise-returning. Uses a
//                                              string id prefixed "rnd-"
//                                              so our own listener claims
//                                              it. Renamed to avoid
//                                              collision with dashboard-
//                                              app.js's `dispatchActionAsync`
//                                              (both files are classic
//                                              scripts; last-one-wins on
//                                              window for top-level fns).
//
// Plugin templates use the `dispatchAndDisplay` action which wraps
// _rendererDispatchAsync and writes the result into a target component.

var _actionCounter = 0;
var _rendererPending = Object.create(null); // id -> { resolve, reject, timer }
var _rendererListenerInstalled = false;

function dispatchAction(messageType, payload) {
  window.parent.postMessage({
    source: 'smartclient-action',
    id: ++_actionCounter,
    messageType: messageType,
    payload: payload || {},
  }, '*');
}

function _installRendererListener() {
  if (_rendererListenerInstalled) return;
  _rendererListenerInstalled = true;
  window.addEventListener('message', function (event) {
    var msg = event.data;
    if (!msg || msg.source !== 'smartclient-action-response') return;
    var id = msg.id;
    if (typeof id !== 'string' || id.slice(0, 4) !== 'rnd-') return;
    var entry = _rendererPending[id];
    if (!entry) return;
    clearTimeout(entry.timer);
    delete _rendererPending[id];
    entry.resolve(msg.response);
  });
}

function _rendererDispatchAsync(messageType, payload, timeoutMs) {
  _installRendererListener();
  var id = 'rnd-' + (++_actionCounter);
  var timeout = typeof timeoutMs === 'number' ? timeoutMs : 60000;
  return new Promise(function (resolve, reject) {
    var timer = setTimeout(function () {
      delete _rendererPending[id];
      reject(new Error('dispatch timeout: ' + messageType + ' (' + timeout + 'ms)'));
    }, timeout);
    _rendererPending[id] = { resolve: resolve, reject: reject, timer: timer };
    window.parent.postMessage({
      source: 'smartclient-action',
      id: id,
      messageType: messageType,
      payload: payload || {},
    }, '*');
  });
}

// ---- Result helpers (used by dispatchAndDisplay) ----

function escapeHtml(str) {
  if (str == null) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function extractByPath(obj, path) {
  if (!path) return obj;
  var parts = String(path).split('.');
  var ref = obj;
  for (var i = 0; i < parts.length; i++) {
    if (ref == null) return undefined;
    ref = ref[parts[i]];
  }
  return ref;
}

var RESULT_FORMATTERS = {
  // Default: pretty-print JSON in a <pre>
  json: function (value) {
    return '<pre style="margin:0;font-size:11px;line-height:1.4;">'
      + escapeHtml(JSON.stringify(value, null, 2)) + '</pre>';
  },
  // Plain string in a <pre> with monospace
  stdoutPre: function (value) {
    return '<pre style="margin:0;font-size:11px;line-height:1.4;color:#0f0;background:#000;padding:8px;border-radius:3px;">'
      + escapeHtml(value == null ? '' : String(value)) + '</pre>';
  },
  // One-line text
  text: function (value) {
    return '<span>' + escapeHtml(value == null ? '' : String(value)) + '</span>';
  },
  // Raw HTML — injected directly without escaping. Use only for trusted
  // content (e.g., HTML generated by a plugin's own Python script).
  rawHtml: function (value) {
    return value == null ? '' : String(value);
  },
};

function formatResult(value, fullResponse, formatterName) {
  var fmt = RESULT_FORMATTERS[formatterName] || RESULT_FORMATTERS.json;
  return fmt(value === undefined ? fullResponse : value);
}

// ---- Cell formatters ----

var FORMATTERS = {
  stateDot: function (value) {
    var colors = {
      running: '#4CAF50', paused: '#FF9800', checkpoint: '#FF9800',
      complete: '#2196F3', cancelled: '#9E9E9E', killed: '#f44336',
      error: '#f44336', registered: '#00BCD4',
    };
    var color = colors[value] || '#666';
    return '<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:'
      + color + ';margin-right:6px;"></span>' + (value || '');
  },
  timestamp: function (value) {
    if (!value) return '';
    var d = new Date(value);
    var mon = (d.getMonth() + 1).toString();
    var day = d.getDate().toString();
    var h = d.getHours().toString().padStart(2, '0');
    var m = d.getMinutes().toString().padStart(2, '0');
    var s = d.getSeconds().toString().padStart(2, '0');
    return mon + '/' + day + ' ' + h + ':' + m + ':' + s;
  },
  elapsed: function (value) {
    if (!value) return '';
    var now = Date.now();
    var ms = now - new Date(value).getTime();
    if (ms < 60000) return Math.round(ms / 1000) + 's ago';
    if (ms < 3600000) return Math.round(ms / 60000) + 'm ago';
    return Math.round(ms / 3600000) + 'h ago';
  },
  progressBar: function (value, record) {
    var step = record ? (record.step || 0) : 0;
    var total = record ? (record.totalSteps || 1) : 1;
    var pct = Math.round((step / total) * 100);
    return '<div style="background:#333;border-radius:3px;height:14px;width:100%;">'
      + '<div style="background:#4CAF50;height:100%;border-radius:3px;width:' + pct + '%;"></div></div>';
  },
};

// ---- Action wiring ----

var ACTION_MAP = {
  'new': function (component, node) {
    component.click = function () {
      var form = resolveRef(node._targetForm);
      if (form) form.editNewRecord();
    };
  },
  'save': function (component, node) {
    component.click = function () {
      var form = resolveRef(node._targetForm);
      var grid = resolveRef(node._targetGrid);
      if (form) {
        form.saveData(function (resp) {
          if (resp.status === 0 && grid) grid.invalidateCache();
        });
      }
    };
  },
  'delete': function (component, node) {
    component.click = function () {
      var grid = resolveRef(node._targetGrid);
      if (!grid) return;
      var record = grid.getSelectedRecord();
      if (record) {
        var ds = grid.getDataSource();
        ds.removeData(record, function () {
          var form = resolveRef(node._targetForm);
          if (form) form.clearValues();
          grid.invalidateCache();
        });
      }
    };
  },
  'select': function (component, node) {
    component.recordClick = function (viewer, record) {
      var form = resolveRef(node._targetForm);
      if (form) form.editRecord(record);
    };
  },
  'dispatch': function (component, node) {
    component.click = function () {
      var payload = Object.assign({}, node._messagePayload || {});
      if (node._payloadFrom) {
        var source = resolveRef(node._payloadFrom);
        if (source) {
          if (source.getSelectedRecord) {
            var record = source.getSelectedRecord();
            if (!record) {
              console.warn('[Renderer] No record selected in', node._payloadFrom, '— skipping', node._messageType);
              return;
            }
            Object.assign(payload, record);
          } else if (source.getValues) {
            Object.assign(payload, source.getValues() || {});
          }
        }
      }
      dispatchAction(node._messageType, payload);
    };
  },
  // ---- DataSource-bound actions (for RestDataSource grids) ----

  'dsFetch': function (component, node) {
    component.click = function () {
      var grid = resolveRef(node._targetGrid);
      if (!grid) return;
      var criteria = {};
      if (node._payloadFrom) {
        var source = resolveRef(node._payloadFrom);
        if (source && source.getValues) criteria = source.getValues() || {};
      }
      grid.fetchData(criteria);
    };
  },
  'dsAdd': function (component, node) {
    component.click = function () {
      var grid = resolveRef(node._targetGrid);
      if (grid) grid.startEditingNew();
    };
  },
  'dsSave': function (component, node) {
    component.click = function () {
      var grid = resolveRef(node._targetGrid);
      if (grid) grid.saveAllEdits();
    };
  },

  /**
   * Like 'dispatch' but waits for the response and writes it into a target
   * component (HTMLFlow, Label, anything with setContents).
   *
   *   {
   *     "_type": "Button",
   *     "title": "Run",
   *     "_action": "dispatchAndDisplay",
   *     "_messageType": "PLUGIN_FOO",
   *     "_messagePayload": {...},        // optional
   *     "_targetCanvas": "outputFlow",   // ID of component to setContents on
   *     "_resultPath": "stdout",         // optional dot-path to extract from response
   *     "_resultFormatter": "stdoutPre"  // optional, see RESULT_FORMATTERS
   *   }
   */
  'dispatchAndDisplay': function (component, node) {
    component.click = function () {
      var target = resolveRef(node._targetCanvas);
      if (!target || !target.setContents) {
        console.warn('[Renderer] dispatchAndDisplay: target', node._targetCanvas, 'has no setContents');
        return;
      }
      var payload = Object.assign({}, node._messagePayload || {});
      target.setContents('<em style="color:#888;">Running ' + escapeHtml(node._messageType) + '...</em>');
      _rendererDispatchAsync(node._messageType, payload, node._timeoutMs).then(function (response) {
        var value = extractByPath(response, node._resultPath);
        var html = formatResult(value, response, node._resultFormatter);
        target.setContents(html);
      }).catch(function (err) {
        target.setContents('<span style="color:#f44336;">Error: ' + escapeHtml(err.message || String(err)) + '</span>');
      });
    };
  },
  /**
   * Stream spawn output progressively into a target component. Uses
   * host.exec.spawnStream and appends each chunk to a Live Console
   * <pre> as it arrives.
   *
   *   {
   *     "_type": "Button",
   *     "title": "Run streaming",
   *     "_action": "streamSpawnAndAppend",
   *     "_cmd": "/bin/sh",
   *     "_args": ["-c", "for i in 1 2 3; do echo $i; sleep 0.5; done"],
   *     "_targetCanvas": "liveConsole"
   *   }
   */
  /**
   * Fetch data via a handler and load it into a ListGrid.
   * The handler must return { data: [...records], totalRows }.
   *
   *   {
   *     "_type": "Button",
   *     "_action": "fetchAndLoadGrid",
   *     "_messageType": "HOST_FETCH_AND_TRANSFORM",
   *     "_messagePayload": { url, jsonPath, fields },
   *     "_targetGrid": "myGrid",
   *     "_statusCanvas": "statusLabel"   // optional: show count/error
   *   }
   */
  'fetchAndLoadGrid': function (component, node) {
    component.click = function () {
      var grid = resolveRef(node._targetGrid);
      var status = node._statusCanvas ? resolveRef(node._statusCanvas) : null;
      if (!grid) {
        console.warn('[Renderer] fetchAndLoadGrid: grid', node._targetGrid, 'not found');
        return;
      }
      if (status && status.setContents) status.setContents('<em style="color:#888;">Loading...</em>');
      // Build payload: static _messagePayload merged with form values from _payloadFrom
      var payload = Object.assign({}, node._messagePayload || {});
      if (node._payloadFrom) {
        var source = resolveRef(node._payloadFrom);
        if (source) {
          // Prefer getValues for forms (DynamicForm has both methods but
          // getSelectedRecord returns null unless a record was loaded);
          // fall back to getSelectedRecord for grids.
          if (source.getValues && source.Class !== 'ListGrid') {
            Object.assign(payload, source.getValues() || {});
          } else if (source.getSelectedRecord) {
            var record = source.getSelectedRecord();
            if (record) Object.assign(payload, record);
          }
        }
      }
      _rendererDispatchAsync(node._messageType, payload, node._timeoutMs).then(function (response) {
        if (response && response.data && Array.isArray(response.data)) {
          // Dynamic column inference: if result has a `columns` array or we can
          // infer from the first row, rebuild the grid's fields before setData.
          // This makes the grid work for ad-hoc queries (e.g. SQL results).
          if (node._dynamicFields && response.data.length > 0) {
            var cols = response.columns || Object.keys(response.data[0]);
            var fields = cols.map(function (c) {
              return { name: c, title: c, width: '*' };
            });
            grid.setFields(fields);
          }
          grid.setData(response.data);
          if (status && status.setContents) {
            status.setContents('<span style="color:#4CAF50;">' + response.totalRows + ' records loaded</span>');
          }
        } else {
          var err = (response && response.error) || 'No data returned';
          if (status && status.setContents) {
            status.setContents('<span style="color:#f44336;">Error: ' + escapeHtml(err) + '</span>');
          }
        }
      }).catch(function (err) {
        if (status && status.setContents) {
          status.setContents('<span style="color:#f44336;">' + escapeHtml(err.message || String(err)) + '</span>');
        }
      });
    };
  },
  /**
   * fetchUrlAndLoadGrid — calls HOST_NETWORK_FETCH with a URL template,
   * parses the JSON response, and loads the array into a grid.
   * Used by storage-backed plugins that can't register SW handlers.
   *
   * Config:
   *   _action: "fetchUrlAndLoadGrid"
   *   _fetchUrl: "https://petstore.swagger.io/v2/pet/findByStatus"
   *   _fetchParams: { "status": "available" }  // or _payloadFrom for form values
   *   _payloadFrom: "filterForm"   // form ID to read query param values from
   *   _targetGrid: "mainGrid"
   *   _statusCanvas: "fetchStatus"
   *   _dynamicFields: true
   *   _flattenObjects: true  // flatten nested objects for grid display
   */
  'fetchUrlAndLoadGrid': function (component, node) {
    component.click = function () {
      var grid = resolveRef(node._targetGrid);
      var status = node._statusCanvas ? resolveRef(node._statusCanvas) : null;
      if (!grid) return;
      if (status && status.setContents) status.setContents('<em style="color:#888;">Loading...</em>');

      // Build query params from form or static config
      var params = Object.assign({}, node._fetchParams || {});
      if (node._payloadFrom) {
        var source = resolveRef(node._payloadFrom);
        if (source && source.getValues) Object.assign(params, source.getValues() || {});
      }

      // Build URL with query string (GET) or body (POST/PUT)
      var url = node._fetchUrl || '';
      var fetchInit = {};
      var method = (node._fetchMethod || 'GET').toUpperCase();

      if (method === 'GET') {
        var qs = Object.entries(params).filter(function (e) { return e[1] != null && e[1] !== ''; })
          .map(function (e) { return encodeURIComponent(e[0]) + '=' + encodeURIComponent(e[1]); }).join('&');
        if (qs) url += (url.includes('?') ? '&' : '?') + qs;
      } else {
        fetchInit = {
          method: method,
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(params),
        };
      }

      _rendererDispatchAsync('HOST_NETWORK_FETCH', { url: url, init: fetchInit, as: 'json' }, node._timeoutMs || 15000).then(function (response) {
        if (!response || !response.ok) {
          var errMsg = 'API returned ' + (response && response.status ? response.status : 'error');
          if (status && status.setContents) status.setContents('<span style="color:#f44336;">' + escapeHtml(errMsg) + '</span>');
          return;
        }
        var data = response.json;
        if (!Array.isArray(data)) data = [data];

        // Flatten nested objects for grid display
        if (node._flattenObjects) {
          data = data.map(function (item) {
            var flat = {};
            for (var k in item) {
              var v = item[k];
              if (v && typeof v === 'object' && !Array.isArray(v)) {
                flat[k] = v.name || v.title || JSON.stringify(v);
              } else if (Array.isArray(v)) {
                flat[k] = v.length + ' items';
              } else {
                flat[k] = v;
              }
            }
            return flat;
          });
        }

        if (node._dynamicFields && data.length > 0) {
          var cols = Object.keys(data[0]);
          grid.setFields(cols.map(function (c) { return { name: c, title: c, width: '*' }; }));
        }
        grid.setData(data);
        if (status && status.setContents) {
          status.setContents('<span style="color:#4CAF50;">' + data.length + ' records loaded</span>');
        }
      }).catch(function (err) {
        if (status && status.setContents) {
          status.setContents('<span style="color:#f44336;">' + escapeHtml(err.message || String(err)) + '</span>');
        }
      });
    };
  },
  'streamSpawnAndAppend': function (component, node) {
    component.click = function () {
      var target = resolveRef(node._targetCanvas);
      if (!target || !target.setContents) {
        console.warn('[Renderer] streamSpawnAndAppend: target', node._targetCanvas, 'has no setContents');
        return;
      }
      if (typeof window.Host === 'undefined' || !window.Host.get) {
        target.setContents('<span style="color:#f44336;">window.Host not available</span>');
        return;
      }
      var cmd = node._cmd;
      var args = node._args || [];
      var lines = [];
      var openTag = '<pre style="margin:0;font-size:11px;line-height:1.4;color:#0f0;background:#000;padding:8px;border-radius:3px;white-space:pre-wrap;">';
      var closeTag = '</pre>';
      function render() {
        target.setContents(openTag + escapeHtml(lines.join('')) + closeTag);
      }
      lines.push('$ ' + cmd + ' ' + args.join(' ') + '\n');
      render();
      try {
        var handle = window.Host.get().exec.spawnStream(cmd, args);
        handle.onStdout(function (chunk) {
          lines.push(chunk);
          render();
        });
        handle.onError(function (err) {
          lines.push('[error] ' + (err && err.message || String(err)) + '\n');
          render();
        });
        handle.done.then(function (result) {
          lines.push('[exit ' + result.exitCode + ' in ' + Math.round(result.elapsedMs || 0) + 'ms]\n');
          render();
        }).catch(function (err) {
          lines.push('[failed] ' + (err && err.message || String(err)) + '\n');
          render();
        });
      } catch (err) {
        target.setContents('<span style="color:#f44336;">Spawn failed: ' + escapeHtml(err.message || String(err)) + '</span>');
      }
    };
  },
  'scriptPause': function (component, node) {
    component.click = function () {
      var grid = resolveRef(node._targetGrid);
      var record = grid && grid.getSelectedRecord();
      if (record) dispatchAction('SCRIPT_PAUSE', { scriptId: record.id });
    };
  },
  'scriptResume': function (component, node) {
    component.click = function () {
      var grid = resolveRef(node._targetGrid);
      var record = grid && grid.getSelectedRecord();
      if (record) dispatchAction('SCRIPT_RESUME', { scriptId: record.id });
    };
  },
  'scriptCancel': function (component, node) {
    component.click = function () {
      var grid = resolveRef(node._targetGrid);
      var record = grid && grid.getSelectedRecord();
      if (record) {
        var payload = Object.assign(
          { scriptId: record.id, reason: 'Cancelled from SC dashboard' },
          node._messagePayload || {}
        );
        dispatchAction('SCRIPT_CANCEL', payload);
      }
    };
  },
  'scriptStep': function (component, node) {
    component.click = function () {
      var ds = window._dashState;
      if (!ds) return;
      var sid = ds.selectedScript
        ? (ds.selectedScript.scriptId || ds.selectedScript.id)
        : ds.selectedScriptId;
      if (!sid) return;
      var clearAll = (node._messagePayload && node._messagePayload.clearAll) || false;
      // V8 line-level pause: use DBG commands instead of checkpoint SCRIPT_STEP
      if (ds.v8Paused) {
        var msgType = clearAll ? 'DBG_CONTINUE' : 'DBG_STEP_OVER';
        dispatchAction(msgType, { scriptId: sid, pid: ds.v8Pid });
      } else {
        dispatchAction('SCRIPT_STEP', { scriptId: sid, clearAll: clearAll });
      }
    };
  },
  'v8Step': function (component, node) {
    component.click = function () {
      var sid = window._dashState && (window._dashState.selectedScript
        ? (window._dashState.selectedScript.scriptId || window._dashState.selectedScript.id)
        : window._dashState.selectedScriptId);
      var pid = window._dashState && window._dashState.v8Pid;
      if (!sid) return;
      dispatchAction(node._messageType, { scriptId: sid, pid: pid });
    };
  },
  'bridgeConnect': function (component) {
    component.click = function () {
      dispatchAction('BRIDGE_CONNECT', { port: 9876 });
    };
  },
  'bridgeDisconnect': function (component) {
    component.click = function () {
      dispatchAction('BRIDGE_DISCONNECT', {});
    };
  },
  'newSession': function (component) {
    // Wired dynamically in dashboard-app.js loadDashboard()
  },
  'newSchedule': function (component) {
    // Wired dynamically in dashboard-app.js loadDashboard()
  },
  'editSchedule': function (component) {
    // Wired dynamically in dashboard-app.js loadDashboard()
  },
  'debugLaunch': function (component) {
    // Wired dynamically in dashboard-app.js loadDashboard()
  },
  'evalExpression': function (component) {
    // Wired dynamically in dashboard-app.js loadDashboard()
  },
  'idbSync': function (component) {
    // Wired dynamically in dashboard-app.js loadDashboard()
  },
  // ---- Client-side compute action ----
  // Reads form values, evaluates safe math expressions, writes results back.
  // Supports _scheduleType:"amortization" to populate a target grid.
  'compute': function (component, node) {
    component.click = function () {
      var form = resolveRef(node._sourceForm || node._targetForm);
      if (!form) { console.warn('[Renderer] compute: no source form'); return; }
      var vals = form.getValues();

      // Evaluate _formulas: { targetFieldName: "expression" }
      if (node._formulas) {
        var computed = {};
        for (var field in node._formulas) {
          computed[field] = _safeEval(node._formulas[field], vals, computed);
        }
        var targetForm = resolveRef(node._targetForm);
        if (targetForm) {
          for (var f in computed) {
            targetForm.setValue(f, Math.round(computed[f] * 100) / 100);
          }
        }
        // Merge computed into vals for schedule generation
        for (var k in computed) vals[k] = computed[k];
      }

      // Generate amortization schedule if requested
      if (node._scheduleType === 'amortization') {
        var grid = resolveRef(node._targetGrid);
        if (grid) {
          var P = Number(vals[node._principalField || 'loanAmount']) || 0;
          var annualRate = Number(vals[node._rateField || 'annualRate']) || 0;
          var years = Number(vals[node._termField || 'termYears']) || 0;
          var r = annualRate / 100 / 12;
          var n = years * 12;
          var monthly = r > 0 ? P * (r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1) : (n > 0 ? P / n : 0);
          var schedule = [];
          var balance = P;
          for (var i = 1; i <= n; i++) {
            var interest = balance * r;
            var principal = monthly - interest;
            balance -= principal;
            if (balance < 0) balance = 0;
            var dt = new Date();
            dt.setMonth(dt.getMonth() + i);
            schedule.push({
              id: i,
              number: i,
              date: (dt.getMonth() + 1) + '/' + dt.getFullYear(),
              payment: Math.round(monthly * 100) / 100,
              principal: Math.round(principal * 100) / 100,
              interest: Math.round(interest * 100) / 100,
              balance: Math.round(balance * 100) / 100,
            });
          }
          grid.setData(schedule);
        }
      }
    };
  },
  // Clear form fields
  'clear': function (component, node) {
    component.click = function () {
      var form = resolveRef(node._targetForm);
      if (form) form.clearValues();
      var grid = resolveRef(node._targetGrid);
      if (grid) grid.setData([]);
    };
  },
};

// ---- Safe expression evaluator (no eval, no Function) ----
// Supports: numbers, field names, +, -, *, /, **, Math.pow/round/floor/ceil/abs/min/max
function _safeEval(expr, vars, computed) {
  var all = {};
  for (var k in vars) all[k] = Number(vars[k]) || 0;
  for (var c in computed) all[c] = Number(computed[c]) || 0;

  var pos = 0;
  var str = String(expr).replace(/\s+/g, '');

  function peek() { return str[pos]; }
  function advance() { return str[pos++]; }
  function isDigit(ch) { return ch >= '0' && ch <= '9'; }
  function isAlpha(ch) { return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || ch === '_'; }

  function parseNumber() {
    var s = pos;
    while (pos < str.length && (isDigit(str[pos]) || str[pos] === '.')) pos++;
    return parseFloat(str.slice(s, pos));
  }

  function parseIdent() {
    var s = pos;
    while (pos < str.length && (isAlpha(str[pos]) || isDigit(str[pos]))) pos++;
    return str.slice(s, pos);
  }

  function parsePrimary() {
    var ch = peek();
    if (ch === '(') { advance(); var v = parseAddSub(); advance(); return v; }
    if (ch === '-') { advance(); return -parsePrimary(); }
    if (isDigit(ch) || ch === '.') return parseNumber();
    if (isAlpha(ch)) {
      var name = parseIdent();
      if (name === 'Math' && peek() === '.') {
        advance(); // '.'
        var fn = parseIdent();
        if (peek() === '(') {
          advance(); // '('
          var args = [parseAddSub()];
          while (peek() === ',') { advance(); args.push(parseAddSub()); }
          advance(); // ')'
          if (typeof Math[fn] === 'function') return Math[fn].apply(null, args);
          return NaN;
        }
        return typeof Math[fn] === 'number' ? Math[fn] : NaN;
      }
      // Check for function-like call: pow(x, y)
      if (peek() === '(' && typeof Math[name] === 'function') {
        advance();
        var a2 = [parseAddSub()];
        while (peek() === ',') { advance(); a2.push(parseAddSub()); }
        advance();
        return Math[name].apply(null, a2);
      }
      return all.hasOwnProperty(name) ? all[name] : 0;
    }
    return 0;
  }

  function parsePower() {
    var left = parsePrimary();
    while (pos + 1 < str.length && str[pos] === '*' && str[pos + 1] === '*') {
      pos += 2; left = Math.pow(left, parsePrimary());
    }
    return left;
  }

  function parseMulDiv() {
    var left = parsePower();
    while (peek() === '*' || peek() === '/') {
      var op = advance();
      left = op === '*' ? left * parsePower() : left / parsePower();
    }
    return left;
  }

  function parseAddSub() {
    var left = parseMulDiv();
    while (peek() === '+' || peek() === '-') {
      var op = advance();
      left = op === '+' ? left + parseMulDiv() : left - parseMulDiv();
    }
    return left;
  }

  try { return parseAddSub(); }
  catch (e) { console.warn('[Renderer] Formula error:', expr, e); return NaN; }
}

function wireAction(component, node) {
  var action = node._action;
  if (!action) return;
  var handler = ACTION_MAP[action];
  if (handler) {
    handler(component, node);
  } else {
    console.warn('[Renderer] Unknown action:', action);
  }
}

// ---- DataSource creation ----

// Allow RestDataSource to make cross-origin calls (sandbox has null origin,
// bridge server is on localhost:9876). Without this, SmartClient shows a warning
// dialog and blocks the request.
if (typeof isc !== 'undefined' && isc.RPCManager) {
  isc.RPCManager.allowCrossDomainCalls = true;
}

function createDataSource(dsConfig) {
  var ds;

  if (dsConfig._type === 'RestDataSource' && dsConfig.dataURL) {
    // RestDataSource via fetch() — the sandbox's XHR is blocked cross-origin
    // but fetch() works. We use clientCustom protocol with fetch() internally
    // to call the bridge's /ds/ endpoint which speaks the RestDataSource wire
    // protocol and proxies to Zato.
    var dsUrl = dsConfig.dataURL;
    ds = isc.DataSource.create({
      ID: dsConfig.ID,
      clientOnly: false,
      dataProtocol: 'clientCustom',
      fields: dsConfig.fields,
      transformRequest: function (dsRequest) {
        var self = this;
        var opType = dsRequest.operationType || 'fetch';
        var data = dsRequest.data || {};

        var url = dsUrl + '?_operationType=' + opType;
        var fetchOpts = { headers: { 'Content-Type': 'application/json' } };

        if (opType === 'fetch') {
          // GET with query params
          for (var k in data) {
            if (data[k] != null) url += '&' + encodeURIComponent(k) + '=' + encodeURIComponent(data[k]);
          }
          if (dsRequest.startRow != null) url += '&_startRow=' + dsRequest.startRow;
          if (dsRequest.endRow != null) url += '&_endRow=' + dsRequest.endRow;
          if (dsRequest.sortBy) url += '&_sortBy=' + dsRequest.sortBy;
          fetchOpts.method = 'GET';
        } else {
          // POST for add/update/remove
          fetchOpts.method = 'POST';
          fetchOpts.body = JSON.stringify(Object.assign({ _operationType: opType }, data));
        }

        fetch(url, fetchOpts)
          .then(function (resp) { return resp.json(); })
          .then(function (result) {
            var r = result.response || result;
            self.processResponse(dsRequest.requestId, {
              status: r.status || 0,
              startRow: r.startRow || 0,
              endRow: r.endRow || (r.data ? r.data.length - 1 : 0),
              totalRows: r.totalRows || (r.data ? r.data.length : 0),
              data: r.data || [],
            });
          })
          .catch(function (err) {
            console.error('[DS] fetch error:', err.message);
            self.processResponse(dsRequest.requestId, { status: -1, data: err.message });
          });
      },
    });
  } else {
    // Default: clientCustom protocol (routed through postMessage → extension → bridge)
    ds = isc.DataSource.create({
      ID: dsConfig.ID,
      dataProtocol: 'clientCustom',
      fields: dsConfig.fields,
      transformRequest: function (dsRequest) {
        sendDSRequest(dsRequest).then(function (resp) {
          this.processResponse(dsRequest.requestId, {
            status: resp.status || 0,
            data: resp.data,
            totalRows: resp.totalRows,
          });
        }.bind(this));
      },
    });
  }

  generatedDataSources.push(ds);
  return ds;
}

// ---- Recursive component creation ----

function createComponent(node, nodePath) {
  if (!node || !node._type) return null;

  // Attach path for inspector click-to-select
  if (nodePath) node._nodePath = nodePath;

  var type = node._type;
  if (!ALLOWED_TYPES.has(type)) {
    console.warn('[Renderer] Blocked type:', type);
    return null;
  }

  if (!isc[type]) {
    console.warn('[Renderer] Unknown SmartClient class:', type);
    return null;
  }

  // Build config — strip _-prefixed meta keys
  var config = {};
  for (var key in node) {
    if (key.charAt(0) === '_') continue;
    if (key === 'members' || key === 'portlets' || key === 'tabs') continue;
    config[key] = node[key];
  }

  // Apply _formatter to ListGrid/ForgeListGrid fields
  if ((type === 'ListGrid' || type === 'ForgeListGrid') && Array.isArray(config.fields)) {
    config.fields = config.fields.map(function (field) {
      if (field._formatter && FORMATTERS[field._formatter]) {
        var fn = FORMATTERS[field._formatter];
        return Object.assign({}, field, {
          formatCellValue: function (value, record) { return fn(value, record); },
          _formatter: undefined,
        });
      }
      return field;
    });
  }

  // Recursively create members (skip for PortalLayout — uses portlets instead)
  if (Array.isArray(node.members) && type !== 'PortalLayout') {
    config.members = [];
    for (var i = 0; i < node.members.length; i++) {
      var childPath = (nodePath || 'layout') + '.members[' + i + ']';
      var child = createComponent(node.members[i], childPath);
      if (child) config.members.push(child);
    }
  }

  // TabSet: create each tab's pane through createComponent so components get registered
  if (type === 'TabSet' && Array.isArray(node.tabs)) {
    config.tabs = node.tabs.map(function (tab, tabIdx) {
      var tabCfg = {};
      for (var k in tab) {
        if (k !== 'pane') tabCfg[k] = tab[k];
      }
      if (tab.pane) {
        var panePath = (nodePath || 'layout') + '.tabs[' + tabIdx + '].pane';
        tabCfg.pane = tab.pane._type ? createComponent(tab.pane, panePath) : tab.pane;
      }
      return tabCfg;
    });
  }

  // Create the component
  var component = isc[type].create(config);

  // PortalLayout: create and place portlets after layout exists
  if (type === 'PortalLayout' && Array.isArray(node.portlets)) {
    for (var p = 0; p < node.portlets.length; p++) {
      var pNode = node.portlets[p];
      var col = pNode._column || 0;
      var row = pNode._row || 0;
      var portletPath = (nodePath || 'layout') + '.portlets[' + p + ']';
      var portlet = createComponent(pNode, portletPath);
      if (portlet) component.addPortlet(portlet, col, row);
    }
  }

  // Register by ID for cross-references
  if (node.ID) {
    componentRegistry[node.ID] = component;
  }

  // Wire actions after creation (needs component reference)
  wireAction(component, node);

  // Inspector click-to-select: attach mouseDown handler for components with IDs
  if (node.ID && component.addProperties && node._nodePath) {
    (function (nodePath) {
      component.addProperties({
        mouseDown: function () {
          if (typeof InspectorUI !== 'undefined' && InspectorUI.isVisible()) {
            InspectorUI.selectByPath(nodePath);
          }
          return true; // allow default SC handling to continue
        },
      });
    })(node._nodePath);
  }

  generatedComponents.push(component);
  return component;
}

// ---- Lifecycle ----

function clearGeneratedUI() {
  // Destroy components in reverse order
  for (var i = generatedComponents.length - 1; i >= 0; i--) {
    try {
      if (generatedComponents[i] && generatedComponents[i].destroy) {
        generatedComponents[i].destroy();
      }
    } catch (e) {
      // Component may already be destroyed by parent
    }
  }
  generatedComponents = [];

  // Destroy DataSources
  for (var j = generatedDataSources.length - 1; j >= 0; j--) {
    try {
      if (generatedDataSources[j] && generatedDataSources[j].destroy) {
        generatedDataSources[j].destroy();
      }
    } catch (e) {
      // ignore
    }
  }
  generatedDataSources = [];

  // Clear registry
  for (var key in componentRegistry) {
    delete componentRegistry[key];
  }
}

// ---- Real-time DS invalidation (SC-3) ----

var _dsDebounceTimers = {};

function invalidateDSCaches(dsId) {
  if (_dsDebounceTimers[dsId]) return;           // already scheduled
  _dsDebounceTimers[dsId] = setTimeout(function () {
    delete _dsDebounceTimers[dsId];
    var ds = isc.DataSource.get(dsId);
    if (!ds) return;
    for (var i = 0; i < generatedComponents.length; i++) {
      var comp = generatedComponents[i];
      if (comp && !comp.destroyed && comp.getDataSource
          && comp.getDataSource() === ds && comp.invalidateCache) {
        comp.invalidateCache();
      }
    }
  }, 500);
}

// ---- Capabilities: skin picker ToolStrip ----

var SKIN_LIST = [
  'Tahoe', 'Obsidian', 'Graphite', 'Stratus', 'Simplicity', 'SilverWave',
  'Enterprise', 'EnterpriseBlue', 'Cascade', 'TreeFrog', 'BlackOps',
  'Twilight', 'fleet', 'Cupertino', 'Shiva', 'ShivaBlue', 'ShivaDark',
  'Mobile', 'SmartClient',
];

function createCapabilitiesBar(options) {
  var members = [];

  if (options.capabilities && options.capabilities.skinPicker) {
    var currentSkin = options.skin || (typeof _skinName !== 'undefined' ? _skinName : 'Tahoe');

    var valueMap = {};
    for (var i = 0; i < SKIN_LIST.length; i++) {
      valueMap[SKIN_LIST[i]] = SKIN_LIST[i];
    }

    var skinForm = isc.DynamicForm.create({
      width: 180,
      numCols: 2,
      colWidths: [40, '*'],
      fields: [{
        name: 'skin',
        title: 'Skin',
        editorType: 'SelectItem',
        valueMap: valueMap,
        defaultValue: currentSkin,
        width: 130,
        changed: function (form, item, value) {
          window.parent.postMessage({ source: 'smartclient-skin-change', skin: value }, '*');
        },
      }],
    });
    members.push(skinForm);
  }

  if (members.length === 0) return null;

  var bar = isc.ToolStrip.create({
    width: '100%',
    height: 32,
    members: members,
  });
  generatedComponents.push(bar);
  return bar;
}

// ---- Entry point ----

function renderConfig(config, options) {
  clearGeneratedUI();

  options = options || {};

  // Create DataSources first
  if (config.dataSources) {
    for (var i = 0; i < config.dataSources.length; i++) {
      createDataSource(config.dataSources[i]);
    }
  }

  // Create component tree
  var mainLayout = null;
  if (config.layout) {
    mainLayout = createComponent(config.layout, 'layout');
  }

  // Inject capabilities bar if enabled
  var capBar = createCapabilitiesBar(options);
  if (capBar && mainLayout) {
    var wrapper = isc.VLayout.create({
      width: '100%',
      height: '100%',
      members: [capBar, mainLayout],
    });
    generatedComponents.push(wrapper);
    // Ensure original layout fills remaining space
    mainLayout.setHeight('*');
  }

  // Deferred cross-reference resolution (for components that reference others by ID)
  for (var i = 0; i < generatedComponents.length; i++) {
    var comp = generatedComponents[i];
    if (!comp || comp.destroyed) continue;

    // ForgeFilterBar: resolve targetGrid string to live reference
    if (comp.getClassName && comp.getClassName() === 'ForgeFilterBar' && typeof comp.targetGrid === 'string') {
      var gridRef = resolveRef(comp.targetGrid);
      if (gridRef) {
        comp.targetGrid = gridRef;
      }
    }
  }

  // A11y enhancement pass
  if (typeof Agentiface !== 'undefined' && Agentiface.A11y) {
    for (var j = 0; j < generatedComponents.length; j++) {
      Agentiface.A11y.enhance(generatedComponents[j]);
    }
  }

  console.log('[Renderer] Created', generatedComponents.length, 'components,',
    generatedDataSources.length, 'dataSources');
}
