#!/usr/bin/env node
/**
 * adapt-to-repo.mjs — Export Agentidev knowledge to any target repository.
 *
 * Detects what the target repo uses (SmartClient, bridge, etc.) and generates
 * tool-native context files so Claude Code, Cursor, and Copilot can tap into
 * CR's indexed knowledge (LanceDB showcase examples, patterns, CLI access).
 *
 * No MCP dependency — everything works via bridge CLI (shell commands).
 *
 * Usage:
 *   node packages/ai-context/adapt.mjs --repo=/path/to/target
 *   node packages/ai-context/adapt.mjs --repo=/path/to/target --check
 *   node packages/ai-context/adapt.mjs --repo=/path/to/target --modules=smartclient,bridge
 *   node packages/ai-context/adapt.mjs --repo=/path/to/target --force   # skip detection
 *   node packages/ai-context/adapt.mjs --repo=/path/to/target --clean   # remove generated files
 *
 * Generates (prefixed cr- to avoid collisions with repo-owned files):
 *   .claude/commands/cr-search.md                      — /cr-search command
 *   .claude/skills/cr-smartclient/SKILL.md             — auto-triggered SC skill
 *   .cursor/rules/cr-smartclient.mdc                   — Cursor SC rule
 *   .github/instructions/cr-smartclient.instructions.md — Copilot SC instruction
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CR_ROOT = join(__dirname, '..', '..');
const BRIDGE_CLI = join(CR_ROOT, 'packages', 'bridge', 'claude-client.mjs');
const SHOWCASE_INDEX = join(CR_ROOT, 'packages', 'bridge', 'scripts', 'sc-showcase-index.md');

const HEADER = '<!-- Generated by agentidev adapt script. Do not edit directly. -->\n';
const REGEN_CMD = (repo) => `<!-- Regenerate: cd ${CR_ROOT} && node packages/ai-context/adapt.mjs --repo=${repo} -->\n`;

// ---------------------------------------------------------------------------
// CLI args
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const repoArg = args.find(a => a.startsWith('--repo='));
const modulesArg = args.find(a => a.startsWith('--modules='));
const CHECK = args.includes('--check');
const FORCE = args.includes('--force');
const CLEAN = args.includes('--clean');

if (!repoArg) {
  console.error('Usage: node packages/ai-context/adapt.mjs --repo=/path/to/target');
  process.exit(1);
}

const TARGET = resolve(repoArg.split('=').slice(1).join('='));
if (!existsSync(TARGET)) {
  console.error(`Target repo not found: ${TARGET}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Module detection
// ---------------------------------------------------------------------------

const MODULES = {
  smartclient: {
    name: 'SmartClient',
    detect: (repo) => {
      // Check for SC-related files in src/ (exclude node_modules)
      try {
        const result = execSync(
          `grep -rl "isc\\." --include="*.ts" --include="*.tsx" --include="*.js" --include="*.html" ${join(repo, 'src')} 2>/dev/null | head -1`,
          { encoding: 'utf8', timeout: 5000 }
        ).trim();
        if (result) return true;
      } catch { /* no matches */ }

      // Check for SC type declarations
      if (existsSync(join(repo, 'src', 'frontend', 'types', 'smartclient.d.ts'))) return true;

      // Check for agentiface/forge
      try {
        const result = execSync(
          `grep -rl "forge-\\|agentiface\\|ForgeListGrid" --include="*.js" --include="*.ts" --include="*.html" ${join(repo, 'src')} 2>/dev/null | head -1`,
          { encoding: 'utf8', timeout: 5000 }
        ).trim();
        if (result) return true;
      } catch { /* no matches */ }

      // Check for smartclient-app directory
      if (existsSync(join(repo, 'extension', 'smartclient-app'))) return true;

      return false;
    },
    generate: generateSmartClientModule,
  },
};

// ---------------------------------------------------------------------------
// Detect which modules apply
// ---------------------------------------------------------------------------

const forceModules = modulesArg
  ? modulesArg.split('=')[1].split(',')
  : null;

function detectModules() {
  const detected = [];
  for (const [id, mod] of Object.entries(MODULES)) {
    if (FORCE || (forceModules && forceModules.includes(id)) || mod.detect(TARGET)) {
      detected.push(id);
    }
  }
  return detected;
}

// ---------------------------------------------------------------------------
// File write/check/clean helpers
// ---------------------------------------------------------------------------

const generatedFiles = [];

function ensureDir(filePath) {
  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function writeOrCheck(relPath, content) {
  const absPath = join(TARGET, relPath);
  generatedFiles.push(relPath);

  if (CLEAN) {
    if (existsSync(absPath)) {
      rmSync(absPath);
      console.log(`  removed ${relPath}`);
    }
    return true;
  }

  if (CHECK) {
    if (!existsSync(absPath)) {
      console.error(`MISSING: ${relPath}`);
      return false;
    }
    const existing = readFileSync(absPath, 'utf8');
    if (existing !== content) {
      console.error(`STALE: ${relPath}`);
      return false;
    }
    return true;
  }

  ensureDir(absPath);
  writeFileSync(absPath, content, 'utf8');
  console.log(`  wrote ${relPath}`);
  return true;
}

// ---------------------------------------------------------------------------
// SmartClient module generator
// ---------------------------------------------------------------------------

function generateSmartClientModule() {
  const files = {};
  const h = HEADER + REGEN_CMD(TARGET);

  // ---- Claude Code: /cr-search command ----
  files['.claude/commands/cr-search.md'] = `${h}
# SmartClient Showcase Search

Search 627 indexed SmartClient showcase examples with neural embeddings (all-MiniLM-L6-v2, 384-dim vectors) stored in LanceDB.

## Search Command

\`\`\`bash
node ${BRIDGE_CLI} search '{"query":"<natural language query>","limit":5}'
\`\`\`

### Parameters

| Field | Type | Default | Description |
|-------|------|---------|-------------|
| query | string | required | Natural language search query |
| limit | number | 10 | Max results to return |
| threshold | number | 0.3 | Minimum similarity score (0-1) |
| queryKeywords | string[] | [] | SC component names to boost (lowercase) |

### Result Fields

Each result contains:
- **title**: Example title
- **url**: \`smartclient://showcase/<exampleId>\`
- **score**: Similarity score (higher = better match)
- **text**: Full source code + description + DataSource XML
- **keywords**: SC components used (e.g. ListGrid, DynamicForm)
- **metadata**: \`{ category, exampleId, hasDataSource, source }\`

### Example Queries

\`\`\`bash
# By component
node ${BRIDGE_CLI} search '{"query":"ListGrid with frozen columns","limit":5}'

# By pattern
node ${BRIDGE_CLI} search '{"query":"master-detail grid with form editing","limit":5}'

# By feature
node ${BRIDGE_CLI} search '{"query":"drag and drop reorder rows","limit":5}'

# With keyword boost
node ${BRIDGE_CLI} search '{"query":"dependent selects","limit":5,"queryKeywords":["selectitem","dynamicform"]}'
\`\`\`

## Workflow

1. Search for relevant examples using the CLI above
2. Read the \`text\` field from top results — it contains full working source code
3. Adapt the code to the current requirements
4. Reference \`metadata.exampleId\` so the user can view it in the showcase

## Requires

Bridge server must be running: \`cd ${CR_ROOT} && npm run bridge &\`

## User Request

$ARGUMENTS
`;

  // ---- Claude Code: auto-triggered SC skill ----
  files['.claude/skills/cr-smartclient/SKILL.md'] = `${h}
# SmartClient Development (Agentidev Knowledge Base)

This skill provides access to 627 indexed SmartClient showcase examples via neural vector search. Use it when building, modifying, or debugging SmartClient components.

## When to Search

BEFORE writing SmartClient code, search for relevant patterns:
- Building a new component? Search for that component type
- Implementing a feature? Search for that feature pattern
- Debugging SC behavior? Search for similar configurations

## How to Search

\`\`\`bash
node ${BRIDGE_CLI} search '{"query":"<describe what you need>","limit":5}'
\`\`\`

The bridge server at \`${CR_ROOT}\` must be running (\`npm run bridge\`).

Each result returns full source code in the \`text\` field — extract and adapt the pattern.

## SmartClient Quick Reference

### Component Creation
- Use \`isc.ClassName.create({ ... })\` for all components
- Set \`autoDraw: false\` when creating components to add to layouts
- Use \`ID\` property for cross-component references

### Core Components
| Widget | Use For | Key Props |
|--------|---------|-----------|
| ListGrid | Data tables | fields, dataSource, canEdit, showFilterEditor |
| TreeGrid | Hierarchical | data (Tree), showConnectors, treeFieldTitle |
| DynamicForm | Input forms | fields, values, numCols, itemChanged |
| Window | Modals | title, isModal, autoCenter, items |
| TabSet | Tabbed UI | tabs, tabBarPosition, tabSelected |
| DataSource | Data binding | clientOnly, fields, cacheAllData |
| VLayout/HLayout | Arrangement | members, layoutMargin, membersMargin |
| SectionStack | Collapsible | sections, visibilityMode |
| ToolStrip | Toolbar | members (ToolStripButton, ToolStripSeparator) |
| Menu | Context menu | data (items with title, click, submenu) |

### DataSource Operations
- \`fetchData(criteria, callback)\` — fetch with optional filter
- \`addData(record, callback)\` — create
- \`updateData(record, callback)\` — update (must include primary key)
- \`removeData(record, callback)\` — delete
- \`setCacheData(array)\` — bulk load for clientOnly DS
- \`invalidateCache()\` — force refresh on next fetch

### Layout Patterns
- \`VLayout\` / \`HLayout\` with \`members: []\` for linear arrangement
- \`SplitPane\` for resizable panels
- \`PortalLayout\` for drag-drop tile dashboards
- \`TabSet\` with \`Tab\` members for tabbed interfaces
- Use \`layoutMargin\` and \`membersMargin\` for spacing (not CSS)

### Common Pitfalls
- SC appends to \`<body>\` with high z-index (200K-3M) — conflicts with other frameworks
- \`clientOnly\` DataSource: \`setCacheData()\` does NOT notify grids; call \`grid.fetchData()\` after
- SC clobbers \`window.DataView\` in Simple Names mode — save/restore if using Monaco or other libs
- \`with\` keyword in SC source is incompatible with ESM strict mode — load via \`<script>\` tags
- Tree data: use \`modelType: "children"\` with nested data, NOT \`parentIdField\` (crashes)
`;

  // ---- Cursor: path-scoped rule ----
  files['.cursor/rules/cr-smartclient.mdc'] = `${h}---
description: SmartClient development patterns and 627-example vector search via agentidev bridge
globs: **/*.{ts,tsx,js,html}
alwaysApply: false
---

# SmartClient Development (Agentidev)

## Searching 627 Indexed Examples

Before writing SmartClient code, search for relevant patterns:

\`\`\`bash
node ${BRIDGE_CLI} search '{"query":"<describe what you need>","limit":5}'
\`\`\`

Requires bridge server running: \`cd ${CR_ROOT} && npm run bridge &\`

Results contain full source code in the \`text\` field — extract and adapt.

## SmartClient Core Patterns

- \`isc.ClassName.create({ ... })\` for all components
- \`autoDraw: false\` when adding to layouts
- \`ID\` property for cross-component references via \`isc.Canvas.getById()\`
- DataSource: \`fetchData()\`, \`addData()\`, \`updateData()\`, \`removeData()\`
- Layouts: \`VLayout\`/\`HLayout\` with \`members[]\`, spacing via \`layoutMargin\`/\`membersMargin\`
- Tree data: always \`modelType: "children"\` (not parentIdField)
- \`clientOnly\` DS: call \`grid.fetchData()\` after \`setCacheData()\`

## Common Pitfalls

- SC clobbers \`window.DataView\` in Simple Names mode
- SC appends to \`<body>\` with z-index 200K-3M (framework conflicts)
- \`with\` keyword incompatible with ESM strict mode — load via \`<script>\` tags
- \`setCacheData()\` does NOT notify bound grids — must call \`fetchData()\`
`;

  // ---- Copilot: path-scoped instruction ----
  files['.github/instructions/cr-smartclient.instructions.md'] = `${h}---
applyTo: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.html"]
---

# SmartClient Development (Agentidev)

627 SmartClient showcase examples are indexed with neural embeddings in a local LanceDB.
Search them via CLI before writing SmartClient code:

\`\`\`bash
node ${BRIDGE_CLI} search '{"query":"<describe what you need>","limit":5}'
\`\`\`

Requires bridge server: \`cd ${CR_ROOT} && npm run bridge &\`

## Key SC Patterns
- \`isc.ClassName.create({ ... })\` — all components
- \`autoDraw: false\` — when adding to layouts
- DataSource: \`fetchData()\`, \`addData()\`, \`updateData()\`, \`removeData()\`
- Layouts: \`VLayout\`/\`HLayout\` with \`members[]\`
- Tree: \`modelType: "children"\` with nested data (not parentIdField)
- \`clientOnly\` DS: call \`grid.fetchData()\` after \`setCacheData()\`
`;

  return files;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const modeLabel = CLEAN ? 'Cleaning' : CHECK ? 'Checking' : 'Adapting';
console.log(`${modeLabel} ${TARGET}...`);

// Detect modules
const active = detectModules();

if (active.length === 0) {
  console.log('No applicable modules detected. Use --force or --modules=smartclient to override.');
  process.exit(0);
}

console.log(`Modules: ${active.join(', ')}\n`);

let allFresh = true;

for (const id of active) {
  const mod = MODULES[id];
  console.log(`[${mod.name}]`);
  const files = mod.generate();
  for (const [path, content] of Object.entries(files)) {
    allFresh = writeOrCheck(path, content) && allFresh;
  }
  console.log();
}

// Clean up empty directories after --clean
if (CLEAN) {
  const dirs = [
    '.claude/skills/cr-smartclient',
    '.claude/commands',
    '.cursor/rules',
    '.github/instructions',
  ];
  for (const d of dirs) {
    const absDir = join(TARGET, d);
    try {
      const entries = readdirSync(absDir);
      if (entries.length === 0) {
        rmSync(absDir, { recursive: true });
        console.log(`  removed empty dir ${d}`);
      }
    } catch { /* dir doesn't exist */ }
  }
}

if (CHECK) {
  if (allFresh) {
    console.log('All generated files are up to date.');
    process.exit(0);
  } else {
    console.error(`Run: cd ${CR_ROOT} && node packages/ai-context/adapt.mjs --repo=${TARGET}`);
    process.exit(1);
  }
} else if (!CLEAN) {
  console.log('Done. Generated files are prefixed cr- to avoid collisions with repo-owned files.');
  console.log('The target repo can layer additional hand-written skills/rules on top.');
}
