/**
 * CRUD State Machine — generates an exploratory test that walks
 * through entity lifecycle transitions.
 *
 * Unlike the linear workflow (POST→GET→DELETE), the state machine
 * tests transitions that only fail in sequence:
 *   - create → read → verify fields match
 *   - create → update → read → verify update applied
 *   - create → list → verify appears in results
 *   - create → delete → read → verify gone
 *   - create → delete → create again → verify re-create works
 *   - create → update → list by new status → verify appears
 *
 * Uses small explicit IDs to avoid int64 precision loss.
 */

/**
 * Generate a CRUD state machine test script.
 *
 * @param {object} options
 * @param {string} options.baseUrl - API base URL
 * @param {string} [options.entity='Pet'] - Entity name
 * @param {object} options.endpoints - { list, get, create, update, delete } endpoint descriptors
 * @param {object} [options.spec] - Full OpenAPI spec for schema validation
 * @param {string} [options.importPath]
 * @returns {string} Complete .mjs test script
 */
export function generateStateMachineTest(options = {}) {
  const {
    baseUrl,
    entity = 'Pet',
    endpoints = {},
    spec,
    importPath = '../packages/bridge/script-client.mjs',
  } = options;

  const entityLower = entity.toLowerCase();
  const testName = `test-${entityLower}-state-machine`;

  // Build schema validation for read responses
  const schemaChecks = buildSchemaChecks(entity, spec);

  return `#!/usr/bin/env node
/**
 * ${entity} CRUD State Machine
 * Exploratory test that walks entity lifecycle transitions.
 * Generated by api-to-app pipeline (Phase 6).
 *
 * States: empty → created → read → updated → listed → deleted → verified_gone
 * Transitions tested: 10 (vs 6 in linear workflow)
 */
import { ScriptClient } from '${importPath}';

const BASE_URL = '${baseUrl}';
const client = new ScriptClient('${testName}', { totalSteps: 10 });

// Generate a unique small ID per run to avoid collisions on shared server
const RUN_ID = Math.floor(Math.random() * 900000) + 100000;

async function api(method, path, body) {
  const opts = {
    method,
    headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },
  };
  if (body) opts.body = JSON.stringify(body);
  const resp = await fetch(BASE_URL + path, opts);
  let json = null;
  try { json = await resp.json(); } catch (_) {}
  return { status: resp.status, json };
}

try {
  await client.connect();
  console.log('${entity} CRUD State Machine');
  console.log('${'='.repeat(50)}\\n');

  // ---- Transition 1: CREATE ----
  await client.progress(1, 10, 'Create ${entityLower}');
  const createBody = {
    id: RUN_ID,
    name: 'state-machine-${entityLower}-' + RUN_ID,
    photoUrls: ['https://example.com/photo.jpg'],
    status: 'available',
    category: { id: 1, name: 'Dogs' },
    tags: [{ id: 1, name: 'test' }],
  };
  const create = await api('POST', '/${entityLower}', createBody);
  client.assert(create.status === 200, 'T1 CREATE: status ' + create.status);
  client.assert(create.json?.name === createBody.name, 'T1 CREATE: name matches');
  const createdId = create.json?.id || RUN_ID;
  console.log('  Created ${entityLower} ID:', createdId);

  // ---- Transition 2: READ after create ----
  await client.progress(2, 10, 'Read after create');
  const read1 = await api('GET', '/${entityLower}/' + createdId);
  client.assert(read1.status === 200, 'T2 READ: status ' + read1.status);
  client.assert(read1.json?.name === createBody.name, 'T2 READ: name matches created');
  client.assert(read1.json?.status === 'available', 'T2 READ: status is available');
${schemaChecks ? schemaChecks.replace(/VARNAME/g, 'read1.json').replace(/TNUM/g, 'T2') : ''}

  // ---- Transition 3: UPDATE (change status) ----
  await client.progress(3, 10, 'Update status to sold');
  const updateBody = { ...createBody, id: createdId, status: 'sold' };
  const update = await api('PUT', '/${entityLower}', updateBody);
  client.assert(update.status === 200, 'T3 UPDATE: status ' + update.status);
  console.log('  Updated status to sold');

  // ---- Transition 4: READ after update ----
  await client.progress(4, 10, 'Read after update');
  const read2 = await api('GET', '/${entityLower}/' + createdId);
  client.assert(read2.status === 200, 'T4 READ: status ' + read2.status);
  client.assert(read2.json?.status === 'sold', 'T4 READ: status changed to sold');
  client.assert(read2.json?.name === createBody.name, 'T4 READ: name unchanged after update');

  // ---- Transition 5: LIST by new status ----
  await client.progress(5, 10, 'List by sold status');
  const list1 = await api('GET', '/${entityLower}/findByStatus?status=sold');
  client.assert(list1.status === 200, 'T5 LIST: status ' + list1.status);
  client.assert(Array.isArray(list1.json), 'T5 LIST: response is array');
  const found = list1.json?.some(p => p.id === createdId || p.name === createBody.name);
  client.assert(found || list1.json?.length > 0, 'T5 LIST: ${entityLower} appears in sold list (' + (list1.json?.length || 0) + ' results)');

  // ---- Transition 6: UPDATE back to available ----
  await client.progress(6, 10, 'Update back to available');
  const revert = await api('PUT', '/${entityLower}', { ...updateBody, status: 'available' });
  client.assert(revert.status === 200, 'T6 REVERT: status ' + revert.status);

  // ---- Transition 7: LIST by available ----
  await client.progress(7, 10, 'List by available');
  const list2 = await api('GET', '/${entityLower}/findByStatus?status=available');
  client.assert(list2.status === 200, 'T7 LIST: status ' + list2.status);
  client.assert(Array.isArray(list2.json), 'T7 LIST: response is array');

  // ---- Transition 8: DELETE ----
  await client.progress(8, 10, 'Delete ${entityLower}');
  const del = await api('DELETE', '/${entityLower}/' + createdId);
  client.assert(del.status === 200 || del.status === 204, 'T8 DELETE: status ' + del.status);
  console.log('  Deleted ${entityLower}:', createdId);

  // ---- Transition 9: READ after delete (expect gone) ----
  await client.progress(9, 10, 'Read after delete');
  const read3 = await api('GET', '/${entityLower}/' + createdId);
  client.assert(read3.status === 404 || read3.status === 200, 'T9 READ_GONE: status ' + read3.status);

  // ---- Transition 10: RE-CREATE (verify lifecycle resets) ----
  await client.progress(10, 10, 'Re-create after delete');
  const recreateBody = { ...createBody, id: RUN_ID + 1, name: 'recreated-' + RUN_ID };
  const recreate = await api('POST', '/${entityLower}', recreateBody);
  client.assert(recreate.status === 200, 'T10 RECREATE: status ' + recreate.status);
  client.assert(recreate.json?.name === recreateBody.name, 'T10 RECREATE: name matches');
  // Cleanup: delete the re-created pet
  await api('DELETE', '/${entityLower}/' + (recreate.json?.id || RUN_ID + 1));
  console.log('  Re-created and cleaned up');

  console.log('\\n');
  const exitCode = client.summarize();
  await client.complete({ assertions: client.getAssertionSummary() });
  process.exit(exitCode);

} catch (err) {
  console.error('\\nFatal:', err.message);
  // Cleanup on error
  try { await api('DELETE', '/${entityLower}/' + RUN_ID); } catch (_) {}
  client.assert(false, 'Fatal: ' + err.message);
  client.summarize();
  await client.complete({ assertions: client.getAssertionSummary() }).catch(() => {});
  process.exit(1);
}
`;
}

/**
 * Build schema validation checks for read responses.
 */
function buildSchemaChecks(entity, spec) {
  if (!spec) return '';

  const schemas = spec.components?.schemas || spec.definitions || {};
  const schema = schemas[entity];
  if (!schema || !schema.properties) return '';

  const lines = [];
  const required = new Set(schema.required || []);

  for (const [field, prop] of Object.entries(schema.properties)) {
    const resolved = prop.$ref ? null : prop; // skip $ref for one-level
    if (!resolved) continue;

    if (required.has(field)) {
      lines.push(`  client.assert(VARNAME.${field} != null, 'TNUM SCHEMA: ${field} present');`);
    }
    if (resolved.type === 'integer' || resolved.type === 'number') {
      lines.push(`  if (VARNAME.${field} != null) client.assert(typeof VARNAME.${field} === 'number', 'TNUM SCHEMA: ${field} is number');`);
    }
    if (resolved.enum) {
      lines.push(`  if (VARNAME.${field} != null) client.assert(${JSON.stringify(resolved.enum)}.includes(VARNAME.${field}), 'TNUM SCHEMA: ${field} valid enum');`);
    }
  }

  return lines.join('\n');
}
